# # Enable I2C support
# CONFIG_I2C=y
# CONFIG_SENSOR=y
# CONFIG_SHT4X=y
# CONFIG_CBPRINTF_FP_SUPPORT=y

# # Memory and Stack Configuration
# CONFIG_HEAP_MEM_POOL_SIZE=16384
# CONFIG_MAIN_STACK_SIZE=4096

# # Debugging and Assertions
# CONFIG_DEBUG_OPTIMIZATIONS=y
# CONFIG_ASSERT=y

# # Enable GPIO support
# CONFIG_GPIO=y
# CONFIG_CBPRINTF_FP_SUPPORT=y

# CONFIG_VL53L0X=y
# CONFIG_VCNL4040_ENABLE_ALS=y
# # CONFIG_MHZ19B=y

# # Display Configuration
# CONFIG_DISPLAY=y
# CONFIG_DISPLAY_LOG_LEVEL_DBG=y
# CONFIG_UART_INTERRUPT_DRIVEN=y
# # Enable Logging
# CONFIG_LOG=y
# CONFIG_SSD1306_DEFAULT_CONTRAST=255
# # SSD1306 OLED Display Driver
# CONFIG_SSD1306=y
# # CONFIG_SSD1306_BUFFER_SIZE=1024

# # Console Configuration
# CONFIG_CONSOLE=y
# # Character Framebuffer
# CONFIG_CHARACTER_FRAMEBUFFER=y
# CONFIG_DISPLAY_LOG_LEVEL_DBG=y
# CONFIG_SSD1306_SH1106_COMPATIBLE=y


CONFIG_STDOUT_CONSOLE=y
CONFIG_SHT4X=y
CONFIG_MHZ19B=y
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_CBPRINTF_FP_SUPPORT=y

# Memory and Stack Configuration
CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_MAIN_STACK_SIZE=4096

# Debugging and Assertions
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_ASSERT=y
CONFIG_MULTITHREADING=y
# CONFIG_ENTROPY_GENERATOR=y
# CONFIG_TEST_RANDOM_GENERATOR=y

# Display Configuration
CONFIG_DISPLAY=y
CONFIG_DISPLAY_LOG_LEVEL_DBG=y

# Enable Logging
CONFIG_LOG=y
# CONFIG_REBOOT=y
# SSD1306 OLED Display Driver
CONFIG_SSD1306=y
CONFIG_SSD1306_SH1106_COMPATIBLE=y
CONFIG_SSD1306_DEFAULT_CONTRAST=255

# Console Configuration
CONFIG_CONSOLE=y
# Character Framebuffer
CONFIG_CHARACTER_FRAMEBUFFER=y

CONFIG_VCNL4040=y
CONFIG_VCNL4040_ENABLE_ALS=y
CONFIG_VL53L0X=y