CONFIG_LOG_BACKEND_UART=y
CONFIG_SPI=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_DISK_ACCESS=y
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_PRINTK=y
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SPI_NRFX_RAM_BUFFER_SIZE=512
CONFIG_DISK_DRIVER_SDMMC=y

# UART support
CONFIG_LOG=y
CONFIG_SERIAL=y








